spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      authentication-database: admin
      username: nopecho
      password: nopecho
      database: waiter
      auto-index-creation: true