name: Deploy Server - waiter-api

on:
  push:
    tags:
      - waiter-api-v*.*.*

env:
  BUILD_TARGET: bootstrap-api
  APP_NAME: waiter-api
  DOCKERHUB_PATH: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_PRIVATE_REPO }}

jobs:
  build:
    environment: production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract version from tag
        id: tag_version
        run: echo "version=$(echo ${GITHUB_REF#refs/tags/$APP_NAME-v})" >> $GITHUB_OUTPUT

      - name: Build and Push to DockerHub
        env:
          IMAGE_TAG: ${{ steps.tag_version.outputs.version }}
        run: |
          make build-docker TARGET=$BUILD_TARGET TAG=$DOCKERHUB_PATH:$APP_NAME-$IMAGE_TAG
          docker push $DOCKERHUB_PATH:$APP_NAME-$IMAGE_TAG